[workspace]
resolver = "2"

members = [
    "src/day1",
    "src/day2",
    "src/lib",
]

[workspace.dependencies]
anyhow = "1.0"
lib = { path = "src/lib"}

[workspace.lints.clippy]
let_and_return = "allow"
ptr_arg = "allow"
new_without_default = "allow"
